version: "3.7"

services:
  react-eval:
    container_name: react-eval
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/react-eval'
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true